version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=creditscore
    ports:
      - "3305:3306"

  springboot-eureka:
    image: eurekaserver
    ports:
      - "8761:8761"
    build:
      context: ""
      dockerfile: "EurekaServer/Dockerfile"

  springboot-score:
    image: creditscoreofcustomer
    ports:
      - "8081:8081"
    build:
      context: ""
      dockerfile: "CreditScoreOfCustomer/Dockerfile"
    depends_on:
      - springboot-eureka

  springboot-docker-container:
    image: creditscorecalculator
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/creditscore?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: ""
      dockerfile: "CreditScoreCalculator/Dockerfile"
    depends_on:
      - mysql-standalone
      - springboot-eureka
      - springboot-score


